package constants

const (
	ORDER_TYPE_BUY  = "BUY"
	ORDER_TYPE_SELL = "SELL"

	REGULAR_ORDER_CATEGORY   = "REGULAR"
	STOP_LOSS_ORDER_CATEGORY = "STOP_LOSS"
	GTT_LOSS_ORDER_CATEGORY  = "GTT"

	ORDER_STATUS_PLACED    = "PLACED"
	ORDER_STATUS_EXECUTED  = "EXECUTED"
	ORDER_STATUS_CANCELLED = "CANCELLED"

	EXECUTION_TYPE_MARKET = "MARKET"
	EXECUTION_TYPE_LIMIT  = "LIMIT"
)
